require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe Admin::Terryblr::PagesController do

  before(:each) do
    @request.env["devise.mapping"] = Devise.mappings[:admin]
    sign_in Factory.create(:user_admin)
  end

  describe "GET index" do
    before do
      Factory(:drafted_page, :created_at => 1.month.ago)
      Factory(:drafted_page)
      Factory(:published_page)
      Factory(:published_page)
    end

    it "assigns all published pages as @pages" do
      get :index
      assigns(:pages).all? { |page| page.published?.should be true }
    end

    describe "drafted pages" do
      before do
        get :index, :state => "drafted", :month => Date.today.month, :year => Date.today.year
      end

      it "should assigns only drafted pages as @pages" do
        assigns(:pages).empty?.should_not be true
        assigns(:pages).all? { |page| page.drafted?.should be true }
      end
    end
  end
end